apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: emotion-detector
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: emotion-detector
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/Eknathreddy09/emotion-detector-tap
